### ISSUE TITLE
Statusbar height is hardcoded for Android.

### ISSUE THREAD

**Issue by ericmatte** [Abhijeet-Ashapure/react-native-sliding-up-down-panel#1]
The statusbar height is defined in the code as 25.
On my device, it is 24, and that value can change from one device to another.

Also, there is currently no way to allow the slider to go under the statusbar in Android.

**Comment by ericmatte** [comment]
Fixed in PR #2

**Comment by Abhijeet-Ashapure** [comment]
Thanks Eric, I will look into it.

**Comment by ericmatte** [comment]
Close due to inactivity.
