### ISSUE TITLE
Seems like, that property `slidingPanelLayoutHeight` does not work

### ISSUE THREAD

**Issue by darkchaplain** [Abhijeet-Ashapure/react-native-sliding-up-down-panel#3]
Hello, I've inspected source code and did not find any usage of `slidingPanelLayoutHeight` property, so the only way to control height of sliding panel is manipulation with `headerLayoutHeight` property, but this approach is practically not usable, because header becomes too big. Is there any possibility to make this property work?
<img width="809" alt="screen shot 2018-07-24 at 3 54 53 pm" src="https://user-images.githubusercontent.com/7280838/43139279-ffdad446-8f59-11e8-9b0f-8152a87ee6d4.png">

**Comment by Abhijeet-Ashapure** [comment]
Hi @darkchaplain. Thanks for your concern but as you have read the readme.md "Sliding the panel upto a particular height" would be covered in next version which I am going to release this saturday, July 4, 2018. Can you please wait till date?

**Comment by kar21us** [comment]
@Abhijeet-Ashapure do you mean this saturday August 4, 2018?

**Comment by Abhijeet-Ashapure** [comment]
Yeah Sorry, I meant August 4, 2018

**Comment by kar21us** [comment]
@Abhijeet-Ashapure any updates?

**Comment by IohkNaut** [comment]
Could u update new features :(( i use this lib for my current project.

**Comment by Dominic-Pace** [comment]
@Abhijeet-Ashapure Hey curious if this next version is going to get released? Having this "Sliding the panel up to a particular height" would be extremely useful! Thanks!

**Comment by Abhijeet-Ashapure** [comment]
Sure, I will going to release it this weekend that is March 3, 2019.
Apologies for inconvenience.

**Comment by Graig123git** [comment]
was this featured merged in?

**Comment by Abhijeet-Ashapure** [comment]
Yeah you can test it my friend

**Comment by Graig123git** [comment]
I just tested this with the following code  and its not working, the pannel ignores the set height and still scroll to the top of the screen.

 <SlidingPanel
        headerLayoutHeight = {50}
       
        headerLayout = { () =>
            <View style={styles.headerLayoutStyle}>
              <Text> Awesome sliding panel</Text>
            </View>
        }
        slidingPanelLayoutHeight={50}
        slidingPanelLayout = { () =>
            <View style={styles.slidingPanelLayoutStyle}>
              <ScrollView>
              <ConsentFilterSearch
                currentLocation={region}
                _updateCircle={(e) => this._updateCircle}
                callbackfromParent={this._toggleModalComplete}
              />
            </ScrollView>
            </View>
        }
          />

**Comment by Abhijeet-Ashapure** [comment]
I will check it

**Comment by sunviwo** [comment]
> I just tested this with the following code and its not working, the pannel ignores the set height and still scroll to the top of the screen.
> 
I confirm. `headerLayoutHeight` prop is not working yet. Except of that, it is an awesome library indeed.

**Comment by Abhijeet-Ashapure** [comment]
I will check it out
